// Generated by scripts/build-biome-grid.ts from RESOLVE Ecoregions 2017 (CC-BY 4.0) — do not edit.
// Edit the curated groups in scripts/brazil-biome-ecoregions.ts and regenerate instead.
import type { BiomeId } from './catalogSchema.ts'

/** RESOLVE ECO_ID → EcoFoco Biome. Ecoregions not listed are unsupported for now. */
export const ECOREGION_BIOMES: Readonly<Record<number, BiomeId>> = {
  476: 'amazon', // Madeira-Tapajós moist forests
  505: 'amazon', // Southwest Amazon moist forests
  511: 'amazon', // Uatumã-Trombetas moist forests
  481: 'amazon', // Mato Grosso tropical dry forests
  465: 'amazon', // Guianan lowland moist forests
  507: 'amazon', // Tapajós-Xingu moist forests
  473: 'amazon', // Japurá-Solimões-Negro moist forests
  518: 'amazon', // Xingu-Tocantins-Araguaia moist forests
  474: 'amazon', // Juruá-Purus moist forests
  484: 'amazon', // Negro-Branco moist forests
  508: 'amazon', // Tocantins/Pindare moist forests
  497: 'amazon', // Purus-Madeira moist forests
  496: 'amazon', // Purus várzea
  503: 'amazon', // Solimões-Japurá moist forests
  480: 'amazon', // Marajó várzea
  464: 'amazon', // Guianan Highlands moist forests
  570: 'amazon', // Guianan savanna
  498: 'amazon', // Rio Negro campinarana
  482: 'amazon', // Monte Alegre várzea
  469: 'amazon', // Iquitos várzea
  490: 'amazon', // Pantepui forests & shrublands
  467: 'amazon', // Gurupa várzea
  611: 'amazon', // Amazon-Orinoco-Southern Caribbean mangroves
  439: 'atlantic-forest', // Alto Paraná Atlantic forests
  440: 'atlantic-forest', // Araucaria moist forests
  500: 'atlantic-forest', // Serra do Mar coastal forests
  443: 'atlantic-forest', // Bahia interior forests
  442: 'atlantic-forest', // Bahia coastal forests
  492: 'atlantic-forest', // Pernambuco interior forests
  491: 'atlantic-forest', // Pernambuco coastal forests
  441: 'atlantic-forest', // Atlantic Coast restingas
  616: 'atlantic-forest', // Southern Atlantic Brazilian mangroves
  462: 'atlantic-forest', // Fernando de Noronha-Atol das Rocas moist forests
  509: 'atlantic-forest', // Trindade-Martin Vaz Islands tropical forests
  525: 'caatinga', // Caatinga
  524: 'caatinga', // Brazilian Atlantic dry forests
  445: 'caatinga', // Caatinga Enclaves moist forests
  485: 'caatinga', // Northeast Brazil restingas
  567: 'cerrado', // Cerrado
  540: 'cerrado', // Maranhão Babaçu forests
  566: 'cerrado', // Campos Rupestres montane savanna
  584: 'pantanal', // Pantanal
  529: 'pantanal', // Chiquitano dry forests
  574: 'pampa', // Uruguayan savanna
}
