import amazon from '../catalog/amazon.json'
import atlanticForest from '../catalog/atlantic-forest.json'
import caatinga from '../catalog/caatinga.json'
import cerrado from '../catalog/cerrado.json'
import pampa from '../catalog/pampa.json'
import pantanal from '../catalog/pantanal.json'
import { toLocale } from '../i18n/locale'
import {
  BIOME_IDS,
  type Archetype,
  type BiomeId,
  type CatalogFile,
  type PhotoCredit,
  type Rarity,
  type SpeciesKind,
} from './catalogSchema'
import type { CollectedEntry } from './types'

export {
  ANIMAL_ARCHETYPES,
  PLANT_ARCHETYPES,
  type AnimalArchetype,
  type Archetype,
  type PlantArchetype,
  type Rarity,
  type SpeciesKind,
} from './catalogSchema'

export interface Species {
  id: string
  scientificName: string
  type: SpeciesKind
  rarity: Rarity
  biome: BiomeId[]
  archetype: Archetype
  names: CatalogFile['species'][number]['names']
  descriptions: CatalogFile['species'][number]['descriptions']
  /** Bundled photo URL. */
  image: string
  photo: Omit<PhotoCredit, 'file'>
}

// Generated by scripts/build-species-catalog.ts — regenerate rather than editing these files.
export const CATALOG_FILES = [amazon, atlanticForest, caatinga, cerrado, pantanal, pampa] as CatalogFile[]

const PHOTO_URLS = import.meta.glob<string>('../assets/species/*.webp', { eager: true, query: '?url', import: 'default' })

/** Merges the per-Biome files into one entry per species, tagged with every Biome it appears in. */
export function buildCatalog(files: CatalogFile[], photoUrls: Record<string, string> = PHOTO_URLS): Species[] {
  const byId = new Map<string, Species>()
  const ordered = [...files].sort((a, b) => BIOME_IDS.indexOf(a.biome) - BIOME_IDS.indexOf(b.biome))
  for (const { biome, species } of ordered) {
    for (const { photo, source: _source, ...entry } of species) {
      const known = byId.get(entry.id)
      if (known) {
        known.biome.push(biome)
        continue
      }
      const { file, ...credit } = photo
      byId.set(entry.id, { ...entry, biome: [biome], image: photoUrls[`../assets/species/${file}`] ?? '', photo: credit })
    }
  }
  return [...byId.values()]
}

export const SPECIES_CATALOG: Species[] = buildCatalog(CATALOG_FILES)

export function speciesName(species: Pick<Species, 'names'>, language: string): string {
  return species.names[toLocale(language)]
}

export function speciesDescription(species: Pick<Species, 'descriptions'>, language: string): string {
  return species.descriptions[toLocale(language)]
}

/** Collected species ids that still exist in the catalog: entries for removed species are kept but not shown. */
export function collectedCatalogSpeciesIds(
  entries: CollectedEntry[],
  catalog: Species[] = SPECIES_CATALOG,
): Set<string> {
  const catalogIds = new Set(catalog.map((s) => s.id))
  return new Set(entries.map((e) => e.speciesId).filter((id) => catalogIds.has(id)))
}
