export type SpeciesKind = 'plant' | 'animal'
export type Rarity = 'common' | 'rare' | 'epic'
export type Biome = 'atlantic-forest'

export interface Species {
  id: string
  scientificName: string
  type: SpeciesKind
  rarity: Rarity
  biome: Biome[]
  image: string
  imageLicense: 'CC0' | 'CC-BY'
  imageAttribution?: string
}

export const SPECIES_CATALOG: Species[] = [
  // Plants
  {
    id: 'ipe-amarelo',
    scientificName: 'Handroanthus albus',
    type: 'plant',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/351406107/original.jpeg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Fabrício Mil Homens Riella via GBIF, CC-BY',
  },
  {
    id: 'jacaranda-mimoso',
    scientificName: 'Jacaranda mimosifolia',
    type: 'plant',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/608327053/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'pau-brasil',
    scientificName: 'Paubrasilia echinata',
    type: 'plant',
    rarity: 'epic',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/608953236/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'jequitiba-rosa',
    scientificName: 'Cariniana legalis',
    type: 'plant',
    rarity: 'epic',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/693111344/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Marcio Santos Ferreira via GBIF, CC-BY',
  },
  {
    id: 'palmito-jucara',
    scientificName: 'Euterpe edulis',
    type: 'plant',
    rarity: 'rare',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/618457199/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'canela-guaica',
    scientificName: 'Ocotea puberula',
    type: 'plant',
    rarity: 'rare',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/637605683/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Fabrício Mil Homens Riella via GBIF, CC-BY',
  },
  {
    id: 'ipe-roxo',
    scientificName: 'Handroanthus impetiginosus',
    type: 'plant',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/610840682/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'embauba',
    scientificName: 'Cecropia pachystachya',
    type: 'plant',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/604863863/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Paulo C. O. Cunha via GBIF, CC-BY',
  },
  {
    id: 'guapuruvu',
    scientificName: 'Schizolobium parahyba',
    type: 'plant',
    rarity: 'rare',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/623371192/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'aroeira-pimenteira',
    scientificName: 'Schinus terebinthifolia',
    type: 'plant',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/605176859/original.jpg',
    imageLicense: 'CC0',
  },

  // Animals
  {
    id: 'sagui-de-tufo-preto',
    scientificName: 'Callithrix penicillata',
    type: 'animal',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/605675307/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Paulo Nogueira via GBIF, CC-BY',
  },
  {
    id: 'bem-te-vi',
    scientificName: 'Pitangus sulphuratus',
    type: 'animal',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/604606426/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'gamba-de-orelha-preta',
    scientificName: 'Didelphis aurita',
    type: 'animal',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/609708102/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Daniel Duarte via GBIF, CC-BY',
  },
  {
    id: 'jacu',
    scientificName: 'Penelope obscura',
    type: 'animal',
    rarity: 'rare',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/610209843/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'tucano-de-bico-verde',
    scientificName: 'Ramphastos dicolorus',
    type: 'animal',
    rarity: 'epic',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/605144497/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Lucas Lopes via GBIF, CC-BY',
  },
  {
    id: 'quati',
    scientificName: 'Nasua nasua',
    type: 'animal',
    rarity: 'rare',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/605105456/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'lagarto-teiu',
    scientificName: 'Salvator merianae',
    type: 'animal',
    rarity: 'rare',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/604868901/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'sabia-laranjeira',
    scientificName: 'Turdus rufiventris',
    type: 'animal',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/605467269/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Leonel Roget via GBIF, CC-BY',
  },
  {
    id: 'borboleta-azul',
    scientificName: 'Morpho helenor',
    type: 'animal',
    rarity: 'rare',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/605967817/original.jpg',
    imageLicense: 'CC0',
  },
  {
    id: 'prea',
    scientificName: 'Cavia aperea',
    type: 'animal',
    rarity: 'common',
    biome: ['atlantic-forest'],
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/605551029/original.jpg',
    imageLicense: 'CC-BY',
    imageAttribution: 'Pablo Bombín via GBIF, CC-BY',
  },
]
